### PR TITLE
New api feature

### PR DESCRIPTION
**Pull request by bvdcode**
Hello!
Dear LaserHydra, please, if it possible, add new API

Add API_TryInsertBackpackFromJson
Add API_TryGetBackpackToJson

### CODE REVIEW

**Comment by WheteThunger** [comment]
Thanks for the contribution!

Can you help me understand the use case for this? Is this for synchronizing data across servers?

Also, for visibility, I'm currently working on a major refactor of the plugin, amidst some other projects. I hope to have a beta out in a few weeks time. The current implementation of this PR will have to change a bit to work in the new version. Are you in a rush to get this merged, or could it wait until later in the year?

**Comment by bvdcode** [comment]
Thanks for your reply.
I use this functionality to integrate with my telegram bot, where I can take the backpack to a virtual warehouse and return it back to the game. At the moment, almost the same code that I proposed is implemented and works, so I'm certainly not in a hurry. If you accept my suggestion, it will only be very convenient, since I won't have to implement my code after every plugin update. I think some developers will also like the new APIs.

**Comment by WheteThunger** [comment]
I implemented something like this in b33444021f6d3648b433072a157709011af44c37.

Can you verify it works for your use case?

You can download the latest from the develop branch, or from uMod (see [beta 3.9 thread](https://umod.org/community/backpacks/46314-backpacks-beta-390)).

**Comment by bvdcode** [comment]
> I implemented something like this in [b334440](https://github.com/LaserHydra/Backpacks/commit/b33444021f6d3648b433072a157709011af44c37).
> 
> Can you verify it works for your use case?
> 
> You can download the latest from the develop branch, or from uMod (see [beta 3.9 thread](https://umod.org/community/backpacks/46314-backpacks-beta-390)).

Hi! I am using new API from develop branch, It works :) thank you very much! 
image

**Pull request closed without merging**
